#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16.13

pipelines:
  branches:
    master:
     - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm i
            - npm test
    develop:
     - step:
         name: Deploy to development server
         deployment: development
         script:
           - pipe: atlassian/ssh-run:0.2.2
             variables:
               SSH_USER: 'centos'
               SERVER: 'dev.powermeeter.com'
               COMMAND: 'cd ~/mediasoup-server; pm2 stop all; git pull; source scl_source enable devtoolset-7; npm i; npm run build; pm2 restart all;'