version: 2
jobs:
  build:
    working_directory: ~/mediasoup-server
    docker:
      - image: circleci/node:12.16.3
    steps:
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

  deploy:
    working_directory: ~/mediasoup-server
    docker:
    - image: circleci/node:12.16.3
    steps:
      - add_ssh_keys:
          fingerprints:
            - 73:cb:e0:ae:55:7b:c7:c4:10:b7:5c:ad:01:d3:b2:b7
      - run:
          name: Deploy over SSH
          command: ssh centos@dev.powermeeter.com -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "cd ~/mediasoup-server; pm2 stop all; git pull; yarn; yarn build; pm2 restart all";

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master